### ISSUE TITLE
Can't build: consider inserting 'swift-tools-version:' between the comment marker and the version specifier

### ISSUE THREAD

**Issue by scoutchorton** [PKBeam/RPFX#3]
I'm having issues building which I believe is due to dependency issues. I'm still new to Xcode and Swift so forgive me for not knowing what's going on.

Here are my specs:
 * 2020 M1 Mac Mini
 * macOS Big Sur 11.4
 * Xcode 12.5.1

![image](https://user-images.githubusercontent.com/12214544/127919776-0c4e785a-a709-4ae2-845f-5560a8093e50.png)

I thought it might be because of a [link to your SwordRPC fork folder](https://github.com/PKBeam/RPFX/blob/cb446d18754512fdca0bcb9c1315dbc834e394bd/RPFX.xcodeproj/project.pbxproj#L23) in the project manager, but cloning the repo and selecting the folder didn't fix it.

I'm not sure if RPFX needs to have a Package.swift file (thus why it's not finding the comment), or if the format is wrong in either SwordRPC or IBM's BlueSocket, but I checked and they both seem fine.

There's also [this question](https://stackoverflow.com/questions/67930290/i-would-like-to-display-xcode-on-discord) on StackOverflow which is from [DiscordX](https://github.com/AsadAzam/DiscordX), which seems to just be a fork of RPFX. The poster on StackOverflow seems to be on an M1 Mac as well, so perhaps that's where the issue is coming from.

For now I'll use the app from the releases, but I would like to be able to build it myself.

I also think it would be a cool idea to add a status icon the menu bar, since it appears that there's no indication that it's running. I'd be willing to contribute and submit a PR if I could build!

**Comment by PKBeam** [comment]
I've updated my SwordRPC fork. The issue seemed to be that the previous BlueSocket repo no longer exists, so I changed the URL.

I can now build on my x86 Mac on macOS 11.4 and Xcode 12.5.1 (build 12E507) - let me know if it's fixed for you.

**Comment by scoutchorton** [comment]
Works like a charm!

**Comment by ejjat0909** [comment]
hello
I get the same error, I want to remove it, but it cant. can you help me please
